export interface VegetableList {
  vegetableName: string;
  type: 'leafy' | 'rhizome' | 'flowers';
  prefixCode: string;
  details: { productName: string; code: string; voice: string }[];
}

export const vegetableList: VegetableList[] = [
  {
    vegetableName: '甘藍[高麗菜]',
    type: 'leafy',
    prefixCode: 'LA',
    details: [
      { productName: '初秋', code: 'LA1', voice: '120101' },
      { productName: '改良種', code: 'LA2', voice: '120102' },
      { productName: '甜甘藍', code: 'LA3', voice: '120103' },
      { productName: '紫色[紫高麗菜]', code: 'LA4', voice: '120104' },
      { productName: '甘藍心[高麗菜心]', code: 'LA5', voice: '120105' },
      { productName: '甘藍芽[高麗菜芽]', code: 'LA6', voice: '120106' },
      { productName: '改良尖', code: 'LA7', voice: '120107' },
      { productName: '進口', code: 'LA9', voice: '120109' },
      { productName: '其他', code: 'LA0', voice: '120100' },
    ],
  },
  {
    vegetableName: '小白菜',
    type: 'leafy',
    prefixCode: 'LB',
    details: [
      { productName: '土白菜', code: 'LB1', voice: '120201' },
      { productName: '蚵仔白', code: 'LB2', voice: '120202' },
      { productName: '奶油白', code: 'LB3', voice: '120203' },
      { productName: '水耕', code: 'LB8', voice: '120208' },
      { productName: '其他', code: 'LB0', voice: '120200' },
    ],
  },
  {
    vegetableName: '包心白菜',
    type: 'leafy',
    prefixCode: 'LC',
    details: [
      { productName: '包白[大白菜]', code: 'LC1', voice: '120301' },
      { productName: '成功白', code: 'LC2', voice: '120302' },
      { productName: '包頭蓮[煙台白菜]', code: 'LC3', voice: '120303' },
      { productName: '天津白', code: 'LC5', voice: '120305' },
      { productName: '冬白芽', code: 'LC6', voice: '120306' },
      { productName: '大土', code: 'LC7', voice: '120307' },
      { productName: '進口', code: 'LC9', voice: '120309' },
      { productName: '其他', code: 'LC0', voice: '120300' },
    ],
  },
  {
    vegetableName: '青江白菜',
    type: 'leafy',
    prefixCode: 'LD',
    details: [
      { productName: '小梗', code: 'LD1', voice: '120401' },
      { productName: '大梗', code: 'LD2', voice: '120402' },
      { productName: '水耕', code: 'LD8', voice: '120408' },
    ],
  },
  {
    vegetableName: '皇宮菜',
    type: 'leafy',
    prefixCode: 'LE',
    details: [
      { productName: '小葉', code: 'LE1', voice: '120501' },
      { productName: '大葉', code: 'LE2', voice: '120502' },
    ],
  },
  {
    vegetableName: '蕹菜',
    type: 'leafy',
    prefixCode: 'LF',
    details: [
      { productName: '大葉[空心菜]', code: 'LF1', voice: '120601' },
      { productName: '小葉', code: 'LF2', voice: '120602' },
      { productName: '水蕹菜', code: 'LF3', voice: '120603' },
      { productName: '水耕', code: 'LF8', voice: '120608' },
      { productName: '其他', code: 'LF0', voice: '120600' },
    ],
  },
  {
    vegetableName: '芹菜',
    type: 'leafy',
    prefixCode: 'LG',
    details: [
      { productName: '青梗', code: 'LG1', voice: '120701' },
      { productName: '白梗', code: 'LG2', voice: '120702' },
      { productName: '西洋芹菜', code: 'LG3', voice: '120703' },
      { productName: '山芹菜', code: 'LG4', voice: '120704' },
      { productName: '芹菜管', code: 'LG5', voice: '120705' },
      { productName: '水耕', code: 'LG8', voice: '120708' },
      { productName: '進口', code: 'LG9', voice: '120709' },
    ],
  },
  {
    vegetableName: '菠菜',
    type: 'leafy',
    prefixCode: 'LH',
    details: [
      { productName: '圓葉', code: 'LH1', voice: '120801' },
      { productName: '角葉', code: 'LH2', voice: '120802' },
      { productName: '甜菠菜', code: 'LH3', voice: '120803' },
      { productName: '進口', code: 'LH9', voice: '120809' },
    ],
  },
  {
    vegetableName: '萵苣菜',
    type: 'leafy',
    prefixCode: 'LI',
    details: [
      { productName: '廣東萵[A菜]', code: 'LI1', voice: '120901' },
      { productName: '結球萵', code: 'LI2', voice: '120902' },
      { productName: '本島圓葉', code: 'LI3', voice: '120903' },
      { productName: '本島尖葉', code: 'LI4', voice: '120904' },
      { productName: '油麥菜[大陸妹]', code: 'LI5', voice: '120905' },
      { productName: '蘿美', code: 'LI6', voice: '120906' },
      { productName: '紅捲、綠捲', code: 'LI7', voice: '120907' },
      { productName: '水耕', code: 'LI8', voice: '120908' },
      { productName: '進口', code: 'LI9', voice: '120909' },
      { productName: '其他', code: 'LI0', voice: '120900' },
    ],
  },
  {
    vegetableName: '芥菜',
    type: 'leafy',
    prefixCode: 'LJ',
    details: [
      { productName: '芥菜仁[長年菜心]', code: 'LJ1', voice: '121001' },
      { productName: '大芥菜[長年菜]', code: 'LJ3', voice: '121003' },
      { productName: '小芥菜', code: 'LJ4', voice: '121004' },
      { productName: '翡翠娃娃菜', code: 'LJ5', voice: '121005' },
      { productName: '水耕', code: 'LJ8', voice: '121008' },
    ],
  },
  {
    vegetableName: '芥藍菜',
    type: 'leafy',
    prefixCode: 'LK',
    details: [
      { productName: '', code: 'LK2', voice: '121102' },
      { productName: '芥藍芽', code: 'LK3', voice: '121103' },
      { productName: '水耕', code: 'LK8', voice: '121108' },
      { productName: '其他', code: 'LK0', voice: '121100' },
      { productName: '進口', code: 'LK9', voice: '121109' },
    ],
  },
  {
    vegetableName: '茼萵',
    type: 'leafy',
    prefixCode: 'LL',
    details: [
      { productName: '', code: 'LL1', voice: '121201' },
      { productName: '山茼蒿', code: 'LL2', voice: '121202' },
      { productName: '水耕', code: 'LL8', voice: '121208' },
      { productName: '其他', code: 'LL0', voice: '121200' },
    ],
  },
  {
    vegetableName: '莧菜',
    type: 'leafy',
    prefixCode: 'LM',
    details: [
      { productName: '紅莧菜', code: 'LM1', voice: '121301' },
      { productName: '白莧菜', code: 'LM2', voice: '121302' },
      { productName: '水耕', code: 'LM8', voice: '121308' },
    ],
  },
  {
    vegetableName: '油菜',
    type: 'leafy',
    prefixCode: 'LN',
    details: [
      { productName: '', code: 'LN1', voice: '121401' },
      { productName: '小松菜', code: 'LN2', voice: '121402' },
      { productName: '油菜花', code: 'LN3', voice: '121403' },
    ],
  },
  {
    vegetableName: '甘藷葉[地瓜葉]',
    type: 'leafy',
    prefixCode: 'LO',
    details: [{ productName: '', code: 'LO1', voice: '121501' }],
  },
  {
    vegetableName: '芫荽',
    type: 'leafy',
    prefixCode: 'LP',
    details: [
      { productName: '芫荽', code: 'LP1', voice: '121601' },
      { productName: '進口', code: 'LP9', voice: '121609' },
      { productName: '九層塔', code: 'LP2', voice: '121602' },
      { productName: '羅勒', code: 'LP3', voice: '121603' },
    ],
  },
  {
    vegetableName: '紅鳳菜',
    type: 'leafy',
    prefixCode: 'LQ',
    details: [
      { productName: '紅鳳菜', code: 'LQ1', voice: '121701' },
      { productName: '白鳳菜', code: 'LQ2', voice: '121702' },
    ],
  },
  {
    vegetableName: '塌棵菜',
    type: 'leafy',
    prefixCode: 'LR',
    details: [{ productName: '', code: 'LR1', voice: '121801' }],
  },
  {
    vegetableName: '茴香',
    type: 'leafy',
    prefixCode: 'LS',
    details: [{ productName: '', code: 'LS1', voice: '121901' }],
  },
  {
    vegetableName: '海菜',
    type: 'leafy',
    prefixCode: 'LT',
    details: [
      { productName: '龍鬚菜', code: 'LT1', voice: '122001' },
      { productName: '海帶', code: 'LT2', voice: '122002' },
      { productName: '水蓮', code: 'LT3', voice: '122003' },
    ],
  },
  {
    vegetableName: '菾菜',
    type: 'leafy',
    prefixCode: 'LU',
    details: [{ productName: '茄茉菜', code: 'LU1', voice: '122101' }],
  },
  {
    vegetableName: '巴西利',
    type: 'leafy',
    prefixCode: 'LV',
    details: [
      { productName: '', code: 'LV1', voice: '122201' },
      { productName: '進口', code: 'LV9', voice: '122209' },
    ],
  },
  {
    vegetableName: '蕨菜',
    type: 'leafy',
    prefixCode: 'LX',
    details: [
      { productName: '過貓', code: 'LX1', voice: '122401' },
      { productName: '山蘇', code: 'LX2', voice: '122402' },
    ],
  },
  {
    vegetableName: '西洋菜',
    type: 'leafy',
    prefixCode: 'LY',
    details: [
      { productName: '', code: 'LY1', voice: '122501' },
      { productName: '黑甜仔菜', code: 'LY2', voice: '122502' },
      { productName: '豬母菜', code: 'LY3', voice: '122503' },
      { productName: '人參葉', code: 'LY4', voice: '122504' },
      { productName: '珍珠菜', code: 'LY5', voice: '122505' },
      { productName: '香椿', code: 'LY6', voice: '122506' },
    ],
  },
  {
    vegetableName: '薺菜',
    type: 'leafy',
    prefixCode: 'LZ',
    details: [
      { productName: '', code: 'LZ1', voice: '122601' },
      { productName: '藤三七', code: 'LZ2', voice: '122602' },
    ],
  },

  // 根莖類
  {
    vegetableName: '蘿蔔',
    type: 'rhizome',
    prefixCode: 'SA',
    details: [
      { productName: '梅花[菜頭]', code: 'SA1', voice: '190101' },
      { productName: '椿仔', code: 'SA2', voice: '190102' },
      { productName: '矸仔', code: 'SA3', voice: '190103' },
      { productName: '櫻桃', code: 'SA4', voice: '190104' },
      { productName: '青色', code: 'SA5', voice: '190105' },
      { productName: '白玉', code: 'SA6', voice: '190106' },
      { productName: '甜菜根', code: 'SA7', voice: '190107' },
      { productName: '進口', code: 'SA9', voice: '190109' },
      { productName: '其他', code: 'SA0', voice: '190100' },
    ],
  },
  {
    vegetableName: '胡蘿蔔',
    type: 'rhizome',
    prefixCode: 'SB',
    details: [
      { productName: '未洗', code: 'SB1', voice: '190201' },
      { productName: '清洗', code: 'SB2', voice: '190202' },
      { productName: '進口', code: 'SB9', voice: '190209' },
    ],
  },
  {
    vegetableName: '馬鈴薯',
    type: 'rhizome',
    prefixCode: 'SC',
    details: [
      { productName: '本產', code: 'SC1', voice: '190301' },
      { productName: '進口', code: 'SC9', voice: '190309' },
    ],
  },
  {
    vegetableName: '洋蔥',
    type: 'rhizome',
    prefixCode: 'SD',
    details: [
      { productName: '本產', code: 'SD1', voice: '190401' },
      { productName: '進口', code: 'SD9', voice: '190409' },
    ],
  },
  {
    vegetableName: '青蔥',
    type: 'rhizome',
    prefixCode: 'SE',
    details: [
      { productName: '日蔥', code: 'SE1', voice: '190501' },
      { productName: '北蔥', code: 'SE2', voice: '190502' },
      { productName: '大蔥', code: 'SE3', voice: '190503' },
      { productName: '珠蔥', code: 'SE4', voice: '190504' },
      { productName: '紅蔥頭', code: 'SE5', voice: '190505' },
      { productName: '粉蔥', code: 'SE6', voice: '190506' },
      { productName: '進口蔥', code: 'SE9', voice: '190509' },
    ],
  },
  {
    vegetableName: '韭菜',
    type: 'rhizome',
    prefixCode: 'SF',
    details: [
      { productName: '白頭', code: 'SF1', voice: '190601' },
      { productName: '韭菜黃', code: 'SF2', voice: '190602' },
      { productName: '韭菜花', code: 'SF3', voice: '190603' },
      { productName: '青頭', code: 'SF4', voice: '190604' },
    ],
  },
  {
    vegetableName: '大蒜',
    type: 'rhizome',
    prefixCode: 'SG',
    details: [
      { productName: '硬梗', code: 'SG1', voice: '190701' },
      { productName: '軟梗', code: 'SG2', voice: '190702' },
      { productName: '蒜苔[蒜苗]', code: 'SG3', voice: '190703' },
      { productName: '蔥蒜', code: 'SG4', voice: '190704' },
      { productName: '蒜頭', code: 'SG5', voice: '190705' },
      { productName: '蒜仁[去皮]', code: 'SG6', voice: '190706' },
      { productName: '蒜瓣', code: 'SG7', voice: '190707' },
      { productName: '進口', code: 'SG9', voice: '190709' },
    ],
  },
  {
    vegetableName: '竹筍',
    type: 'rhizome',
    prefixCode: 'SH',
    details: [
      { productName: '麻竹筍', code: 'SH1', voice: '190801' },
      { productName: '綠竹筍', code: 'SH2', voice: '190802' },
      { productName: '桂竹筍', code: 'SH3', voice: '190803' },
      { productName: '孟宗筍', code: 'SH4', voice: '190804' },
      { productName: '烏殼綠', code: 'SH5', voice: '190805' },
      { productName: '箭竹筍', code: 'SH6', voice: '190806' },
      { productName: '去殼', code: 'SH7', voice: '190807' },
      { productName: '進口', code: 'SH9', voice: '190809' },
    ],
  },
  {
    vegetableName: '萵苣莖[A菜心]',
    type: 'rhizome',
    prefixCode: 'SI',
    details: [{ productName: '', code: 'SI1', voice: '190901' }],
  },
  {
    vegetableName: '芋',
    type: 'rhizome',
    prefixCode: 'SJ',
    details: [
      { productName: '麵芋[芋頭]', code: 'SJ1', voice: '191001' },
      { productName: '檳榔心芋', code: 'SJ2', voice: '191002' },
      { productName: '里芋', code: 'SJ3', voice: '191003' },
      { productName: '芋莖', code: 'SJ4', voice: '191004' },
      { productName: '芋角', code: 'SJ5', voice: '191005' },
      { productName: '進口', code: 'SJ9', voice: '191009' },
    ],
  },
  {
    vegetableName: '荸薺',
    type: 'rhizome',
    prefixCode: 'SK',
    details: [
      { productName: '[馬蹄]', code: 'SK1', voice: '191101' },
      { productName: '加工', code: 'SK2', voice: '191102' },
    ],
  },
  {
    vegetableName: '豆薯',
    type: 'rhizome',
    prefixCode: 'SL',
    details: [
      { productName: '[掛薺]', code: 'SL1', voice: '191201' },
      { productName: '雪蓮薯', code: 'SL2', voice: '191202' },
    ],
  },
  {
    vegetableName: '牛蒡',
    type: 'rhizome',
    prefixCode: 'SM',
    details: [
      { productName: '', code: 'SM1', voice: '191301' },
      { productName: '進口', code: 'SM9', voice: '191309' },
    ],
  },
  {
    vegetableName: '蓮藕',
    type: 'rhizome',
    prefixCode: 'SN',
    details: [
      { productName: '', code: 'SN1', voice: '191401' },
      { productName: '蓮子', code: 'SN2', voice: '191402' },
      { productName: '進口', code: 'SN9', voice: '191409' },
    ],
  },
  {
    vegetableName: '甘藷',
    type: 'rhizome',
    prefixCode: 'SO',
    details: [
      { productName: '臺農57號[黃肉]', code: 'SO1', voice: '191501' },
      { productName: '芋仔甘藷', code: 'SO2', voice: '191502' },
      { productName: '臺農66號[紅肉]', code: 'SO3', voice: '191503' },
      { productName: '其他[地瓜]', code: 'SO0', voice: '191500' },
    ],
  },
  {
    vegetableName: '薑',
    type: 'rhizome',
    prefixCode: 'SP',
    details: [
      { productName: '老薑', code: 'SP1', voice: '191601' },
      { productName: '嫩薑', code: 'SP2', voice: '191602' },
      { productName: '粉薑', code: 'SP3', voice: '191603' },
      { productName: '竹薑', code: 'SP4', voice: '191604' },
      { productName: '薑黃', code: 'SP5', voice: '191605' },
      { productName: '其他', code: 'SP0', voice: '191600' },
      { productName: '進口', code: 'SP9', voice: '191609' },
    ],
  },
  {
    vegetableName: '茭白筍',
    type: 'rhizome',
    prefixCode: 'SQ',
    details: [
      { productName: '帶殼', code: 'SQ1', voice: '191701' },
      { productName: '去殼', code: 'SQ3', voice: '191703' },
      { productName: '進口', code: 'SQ9', voice: '191709' },
    ],
  },
  {
    vegetableName: '菱角',
    type: 'rhizome',
    prefixCode: 'SR',
    details: [
      { productName: '生菱角', code: 'SR1', voice: '191801' },
      { productName: '去殼', code: 'SR3', voice: '191803' },
      { productName: '熟菱角', code: 'SR4', voice: '191804' },
    ],
  },
  {
    vegetableName: '大心菜',
    type: 'rhizome',
    prefixCode: 'SS',
    details: [
      { productName: '帶葉[菜心]', code: 'SS1', voice: '191901' },
      { productName: '其他', code: 'SS0', voice: '191900' },
    ],
  },
  {
    vegetableName: '蕎頭',
    type: 'rhizome',
    prefixCode: 'ST',
    details: [{ productName: '露蕎', code: 'ST1', voice: '192001' }],
  },
  {
    vegetableName: '薯蕷',
    type: 'rhizome',
    prefixCode: 'SU',
    details: [
      { productName: '紅薯蕷[山藥]', code: 'SU1', voice: '192101' },
      { productName: '白薯蕷', code: 'SU2', voice: '192102' },
      { productName: '樹薯', code: 'SU3', voice: '192103' },
      { productName: '粉薯', code: 'SU4', voice: '192104' },
      { productName: '其他', code: 'SU0', voice: '192100' },
      { productName: '進口', code: 'SU9', voice: '192109' },
    ],
  },
  {
    vegetableName: '蘆筍',
    type: 'rhizome',
    prefixCode: 'SV',
    details: [
      { productName: '白蘆筍', code: 'SV1', voice: '192201' },
      { productName: '綠蘆筍', code: 'SV2', voice: '192202' },
      { productName: '蘆筍花', code: 'SV3', voice: '192203' },
      { productName: '進口', code: 'SV9', voice: '192209' },
    ],
  },
  {
    vegetableName: '球莖甘藍',
    type: 'rhizome',
    prefixCode: 'SW',
    details: [{ productName: '[大頭菜]', code: 'SW1', voice: '192301' }],
  },
  {
    vegetableName: '芽菜類',
    type: 'rhizome',
    prefixCode: 'SX',
    details: [
      { productName: '綠豆芽', code: 'SX1', voice: '192401' },
      { productName: '黃豆芽', code: 'SX2', voice: '192402' },
      { productName: '豌豆芽', code: 'SX3', voice: '192403' },
      { productName: '苜蓿芽', code: 'SX4', voice: '192404' },
      { productName: '蘿蔔嬰', code: 'SX5', voice: '192405' },
      { productName: '其他', code: 'SX0', voice: '192400' },
    ],
  },
  {
    vegetableName: '慈菇',
    type: 'rhizome',
    prefixCode: 'SY',
    details: [{ productName: '', code: 'SY1', voice: '192501' }],
  },
  {
    vegetableName: '半天筍',
    type: 'rhizome',
    prefixCode: 'SZ',
    details: [
      { productName: '半天筍', code: 'SZ1', voice: '192601' },
      { productName: '甘蔗筍', code: 'SZ2', voice: '192602' },
      { productName: '金針筍', code: 'SZ3', voice: '192603' },
      { productName: '百合', code: 'SZ4', voice: '192604' },
      { productName: '草石蠶[冬蟲夏草]', code: 'SZ5', voice: '192605' },
      { productName: '半天花', code: 'SZ6', voice: '192606' },
      { productName: '晚香玉筍', code: 'SZ7', voice: '192607' },
      { productName: '香茅', code: 'SZ8', voice: '192608' },
    ],
  },

  // 花果菜類
  {
    vegetableName: '黃秋葵',
    type: 'flowers',
    prefixCode: 'FA',
    details: [
      { productName: '[秋葵]', code: 'FA1', voice: '060101' },
      { productName: '樊花', code: 'FA2', voice: '060102' },
      { productName: '瓊花', code: 'FA4', voice: '060104' },
      { productName: '其他花類', code: 'FA0', voice: '060100' },
      { productName: '百果(進口)', code: 'FA9', voice: '060109' },
    ],
  },
  {
    vegetableName: '花椰菜',
    type: 'flowers',
    prefixCode: 'FB',
    details: [
      { productName: '青梗[白花菜]', code: 'FB1', voice: '060201' },
      { productName: '白梗', code: 'FB2', voice: '060202' },
      { productName: '其他', code: 'FB0', voice: '060200' },
      { productName: '進口', code: 'FB9', voice: '060209' },
    ],
  },
  {
    vegetableName: '胡瓜',
    type: 'flowers',
    prefixCode: 'FC',
    details: [
      { productName: '黑刺[台語:刺瓜]', code: 'FC1', voice: '060301' },
      { productName: '改良種[大黃瓜]', code: 'FC2', voice: '060302' },
    ],
  },
  {
    vegetableName: '花胡瓜',
    type: 'flowers',
    prefixCode: 'FD',
    details: [
      { productName: '', code: 'FD1', voice: '060401' },
      { productName: '進口', code: 'FD9', voice: '060409' },
      { productName: '其他[小黃瓜]', code: 'FD0', voice: '060400' },
    ],
  },
  {
    vegetableName: '冬瓜',
    type: 'flowers',
    prefixCode: 'FE',
    details: [
      { productName: '白皮', code: 'FE1', voice: '060501' },
      { productName: '青皮', code: 'FE2', voice: '060502' },
      { productName: '毛瓜', code: 'FE3', voice: '060503' },
      { productName: '其他', code: 'FE0', voice: '060500' },
      { productName: '進口', code: 'FE9', voice: '060509' },
    ],
  },
  {
    vegetableName: '絲瓜',
    type: 'flowers',
    prefixCode: 'FF',
    details: [
      { productName: '[菜瓜]', code: 'FF1', voice: '060601' },
      { productName: '角瓜[澎湖絲瓜]', code: 'FF2', voice: '060602' },
      { productName: '白瓜', code: 'FF3', voice: '060603' },
      { productName: '長絲瓜', code: 'FF4', voice: '060604' },
      { productName: '進口', code: 'FF9', voice: '060609' },
      { productName: '其他', code: 'FF0', voice: '060600' },
    ],
  },
  {
    vegetableName: '苦瓜',
    type: 'flowers',
    prefixCode: 'FG',
    details: [
      { productName: '白大米', code: 'FG1', voice: '060701' },
      { productName: '青大米', code: 'FG2', voice: '060702' },
      { productName: '山苦瓜', code: 'FG3', voice: '060703' },
      { productName: '翠綠', code: 'FG4', voice: '060704' },
      { productName: '進口', code: 'FG9', voice: '060709' },
      { productName: '其他', code: 'FG0', voice: '060700' },
    ],
  },
  {
    vegetableName: '扁蒲',
    type: 'flowers',
    prefixCode: 'FH',
    details: [
      { productName: '長形[蒲仔]', code: 'FH1', voice: '060801' },
      { productName: '圓形', code: 'FH2', voice: '060802' },
      { productName: '花蒲', code: 'FH3', voice: '060803' },
      { productName: '梨子蒲', code: 'FH4', voice: '060804' },
      { productName: '其他', code: 'FH0', voice: '060800' },
    ],
  },
  {
    vegetableName: '茄子',
    type: 'flowers',
    prefixCode: 'FI',
    details: [
      { productName: '胭脂茄', code: 'FI1', voice: '060901' },
      { productName: '麻荸茄', code: 'FI2', voice: '060902' },
      { productName: '日本種', code: 'FI3', voice: '060903' },
      { productName: '其他', code: 'FI0', voice: '060900' },
    ],
  },
  {
    vegetableName: '番茄',
    type: 'flowers',
    prefixCode: 'FJ',
    details: [
      { productName: '黑柿', code: 'FJ1', voice: '061001' },
      { productName: '粉柿', code: 'FJ2', voice: '061002' },
      { productName: '牛蕃茄', code: 'FJ3', voice: '061003' },
      { productName: '其他', code: 'FJ0', voice: '061000' },
    ],
  },
  {
    vegetableName: '甜椒',
    type: 'flowers',
    prefixCode: 'FK',
    details: [
      { productName: '新香', code: 'FK3', voice: '061103' },
      { productName: '彩色種', code: 'FK4', voice: '061104' },
      { productName: '青椒', code: 'FK5', voice: '061105' },
      { productName: '水果彩椒', code: 'FK6', voice: '061106' },
      { productName: '進口', code: 'FK9', voice: '061109' },
      { productName: '其他', code: 'FK0', voice: '061100' },
    ],
  },
  {
    vegetableName: '豌豆',
    type: 'flowers',
    prefixCode: 'FL',
    details: [
      { productName: '白花[荷蘭豆]', code: 'FL1', voice: '061201' },
      { productName: '紅花', code: 'FL2', voice: '061202' },
      { productName: '豆莢', code: 'FL3', voice: '061203' },
      { productName: '豆仁', code: 'FL4', voice: '061204' },
      { productName: '豌豆苗', code: 'FL5', voice: '061205' },
      { productName: '甜豌豆', code: 'FL6', voice: '061206' },
      { productName: '進口', code: 'FL9', voice: '061209' },
    ],
  },
  {
    vegetableName: '菜豆',
    type: 'flowers',
    prefixCode: 'FM',
    details: [
      { productName: '白色[豇豆]', code: 'FM1', voice: '061301' },
      { productName: '青色', code: 'FM2', voice: '061302' },
      { productName: '紅色', code: 'FM3', voice: '061303' },
      { productName: '進口', code: 'FM9', voice: '061309' },
      { productName: '其他', code: 'FM0', voice: '061300' },
    ],
  },
  {
    vegetableName: '敏豆',
    type: 'flowers',
    prefixCode: 'FN',
    details: [
      { productName: '白豆[四季豆]', code: 'FN1', voice: '061401' },
      { productName: '青豆', code: 'FN2', voice: '061402' },
      { productName: '粉豆', code: 'FN3', voice: '061403' },
      { productName: '翼豆', code: 'FN4', voice: '061404' },
      { productName: '醜豆', code: 'FN5', voice: '061405' },
      { productName: '進口', code: 'FN9', voice: '061409' },
      { productName: '其他', code: 'FN0', voice: '061400' },
    ],
  },
  {
    vegetableName: '蠶豆',
    type: 'flowers',
    prefixCode: 'FO',
    details: [
      { productName: '豆莢', code: 'FO1', voice: '061501' },
      { productName: '豆仁', code: 'FO2', voice: '061502' },
    ],
  },
  {
    vegetableName: '萊豆',
    type: 'flowers',
    prefixCode: 'FP',
    details: [
      { productName: '豆莢[皇帝豆]', code: 'FP1', voice: '061601' },
      { productName: '豆仁', code: 'FP2', voice: '061602' },
      { productName: '肉豆(鵲豆)', code: 'FP3', voice: '061603' },
    ],
  },
  {
    vegetableName: '毛豆',
    type: 'flowers',
    prefixCode: 'FQ',
    details: [
      { productName: '豆莢', code: 'FQ1', voice: '061701' },
      { productName: '豆仁', code: 'FQ2', voice: '061702' },
      { productName: '進口', code: 'FQ9', voice: '061709' },
    ],
  },
  {
    vegetableName: '青花苔',
    type: 'flowers',
    prefixCode: 'FR',
    details: [
      { productName: '[青花菜]', code: 'FR1', voice: '061801' },
      { productName: '青花筍', code: 'FR2', voice: '061802' },
      { productName: '進口', code: 'FR9', voice: '061809' },
    ],
  },
  {
    vegetableName: '越瓜',
    type: 'flowers',
    prefixCode: 'FS',
    details: [
      { productName: '', code: 'FS1', voice: '061901' },
      { productName: '加工[醃瓜]', code: 'FS2', voice: '061902' },
      { productName: '其他', code: 'FS0', voice: '061900' },
    ],
  },
  {
    vegetableName: '南瓜',
    type: 'flowers',
    prefixCode: 'FT',
    details: [
      { productName: '木瓜形', code: 'FT1', voice: '062001' },
      { productName: '圓形', code: 'FT2', voice: '062002' },
      { productName: '黃如意[黃節瓜]', code: 'FT3', voice: '062003' },
      { productName: '觀賞', code: 'FT4', voice: '062004' },
      { productName: '青如意[青節瓜]', code: 'FT5', voice: '062005' },
      { productName: '東昇', code: 'FT6', voice: '062006' },
      { productName: '栗子', code: 'FT7', voice: '062007' },
      { productName: '進口', code: 'FT9', voice: '062009' },
      { productName: '其他', code: 'FT0', voice: '062000' },
    ],
  },
  {
    vegetableName: '隼人瓜',
    type: 'flowers',
    prefixCode: 'FU',
    details: [
      { productName: '[佛手瓜]', code: 'FU1', voice: '062101' },
      { productName: '瓜苗[龍鬚菜]', code: 'FU2', voice: '062102' },
      { productName: '石蓮花', code: 'FU3', voice: '062103' },
    ],
  },
  {
    vegetableName: '辣椒',
    type: 'flowers',
    prefixCode: 'FV',
    details: [
      { productName: '紅小', code: 'FV1', voice: '062201' },
      { productName: '青小', code: 'FV2', voice: '062202' },
      { productName: '雞心', code: 'FV3', voice: '062203' },
      { productName: '朝天椒', code: 'FV4', voice: '062204' },
      { productName: '青龍', code: 'FV5', voice: '062205' },
      { productName: '糯米椒', code: 'FV6', voice: '062206' },
      { productName: '進口', code: 'FV9', voice: '062209' },
      { productName: '其他', code: 'FV0', voice: '062200' },
    ],
  },
  {
    vegetableName: '金針花',
    type: 'flowers',
    prefixCode: 'FW',
    details: [
      { productName: '', code: 'FW1', voice: '062301' },
      { productName: '進口', code: 'FW9', voice: '062309' },
      { productName: '洛神花', code: 'FW2', voice: '062302' },
    ],
  },
  {
    vegetableName: '花豆',
    type: 'flowers',
    prefixCode: 'FX',
    details: [
      { productName: '花豆', code: 'FX1', voice: '062401' },
      { productName: '福豆(虎豆)', code: 'FX2', voice: '062402' },
    ],
  },
  {
    vegetableName: '玉米',
    type: 'flowers',
    prefixCode: 'FY',
    details: [
      { productName: '白玉米', code: 'FY1', voice: '062501' },
      { productName: '甜硬殼', code: 'FY2', voice: '062502' },
      { productName: '超甜白[水果玉米]', code: 'FY3', voice: '062503' },
      { productName: '玉米筍', code: 'FY4', voice: '062504' },
      { productName: '糯米黑', code: 'FY5', voice: '062505' },
      { productName: '甜軟殼', code: 'FY6', voice: '062506' },
      { productName: '糯米白', code: 'FY7', voice: '062507' },
      { productName: '白龍王', code: 'FY8', voice: '062508' },
      { productName: '進口', code: 'FY9', voice: '062509' },
      { productName: '其他', code: 'FY0', voice: '062500' },
    ],
  },
  {
    vegetableName: '落花生',
    type: 'flowers',
    prefixCode: 'FZ',
    details: [
      { productName: '生落花生', code: 'FZ1', voice: '062601' },
      { productName: '熟落花生', code: 'FZ2', voice: '062602' },
    ],
  },
];
